// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irmuaqhwmtgbkftqlohx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybXVhcWh3bXRnYmtmdHFsb2h4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NTU2NzQsImV4cCI6MjA2NzMzMTY3NH0.6DX_aLCLCy__18IGOG2DW1vJGkWSw4TJ4gm2eNdn35U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});